name: Test

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "adopt@1.8"

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check format
        run: |
          mkdir -p dist
          sbt -no-colors checkAll > dist/result.txt

      - name: Test
        run: 'sbt "testOnly com.nulabinc.*"'

      - name: Upload sbt result
        uses: actions/upload-artifact@master
        with:
          name: sbt-result
          path: dist

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Notify to Typetalk if success
        if: success()
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":tada: Redmine importer job success :smile:\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
          
      - name: Notify to Typetalk if fail
        if: failure()
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":rage: Redmine importer job failed\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

      - name: Notify to Typetalk if cancelled
        if: cancelled()
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":no_entry: Redmine importer job cancelled\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

